# Your personal GitHub token
github_token: aecaa5500b349cbeb31e4fd604a1d24f795d4ad4
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Europe/Moscow

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: phonebook

# Virtual machine IP
ip: 192.168.83.188

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 512
